### ISSUE TITLE
在企业微信中，请添加toTag的功能

### ISSUE THREAD

**Issue by parkerlu** [zl-php/wechat#1]
企业微信发送图文通知的时候，有toTag的选项，但这个库不支持。请作者添加一下。谢谢。

**Comment by parkerlu** [comment]
因为企业微信只接受tag的ID，所以还需要增加获取id的功能。可以做一个Tag的provider

在 client.php 中增加这个就行了。

  public function list()
    {
        return $this->httpGet('cgi-bin/tag/list');
    }

**Comment by zl-php** [comment]
> 因为企业微信只接受tag的ID，所以还需要增加获取id的功能。可以做一个Tag的provider
> 
> 在 client.php 中增加这个就行了。
> 
> public function list() { return $this->httpGet('cgi-bin/tag/list'); }

好的，我没用到过，就没加，明天（2023-09-08）帮你加上
